# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-03 11:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import portal.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='名称')),
                ('type', models.IntegerField(blank=True, choices=[(1, '男歌手'), (0, '女歌手'), (2, '组合')], null=True, verbose_name='类型')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ArtistAvatar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(height_field='height', null=True, storage=portal.models.FileStorage(), upload_to=portal.models.artist_avatar_upload_to, verbose_name='图片', width_field='width')),
                ('width', models.PositiveIntegerField(blank=True, null=True)),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('artist', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='portal.Artist')),
            ],
        ),
        migrations.CreateModel(
            name='ArtistImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(height_field='height', null=True, storage=portal.models.FileStorage(), upload_to=portal.models.artist_images_upload_to, verbose_name='图片', width_field='width')),
                ('width', models.PositiveIntegerField(blank=True, null=True)),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.Artist')),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='名称')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ExcelLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_start', models.DateTimeField(null=True)),
                ('datetime_end', models.DateTimeField(null=True)),
                ('status', models.IntegerField(blank=True, choices=[(0, '开始'), (1, '成功'), (-1, '失败')], null=True)),
                ('file_excel', models.FileField(null=True, upload_to='')),
                ('file_log', models.FileField(null=True, upload_to='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-datetime_start'],
            },
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='标题')),
                ('number', models.CharField(blank=True, max_length=128, null=True, verbose_name='编号')),
                ('format', models.IntegerField(blank=True, choices=[(1, 'CD'), (2, 'LP'), (3, 'MC'), (4, 'DATA')], null=True, verbose_name='介质')),
                ('release', models.CharField(blank=True, help_text='yyyy', max_length=8, null=True, verbose_name='发布时间')),
                ('producer', models.CharField(blank=True, max_length=128, null=True, verbose_name='监制')),
                ('release_order', models.CharField(blank=True, help_text='yyyy0000', max_length=8, null=True, verbose_name='发布时间排序')),
                ('recorder', models.CharField(blank=True, max_length=128, null=True, verbose_name='录音')),
                ('mixer', models.CharField(blank=True, max_length=128, null=True, verbose_name='混音')),
                ('bandsman', models.TextField(blank=True, null=True, verbose_name='乐手')),
                ('description', models.TextField(blank=True, null=True, verbose_name='说明')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('artists', models.ManyToManyField(blank=True, to='portal.Artist', verbose_name='歌手')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='portal.Company', verbose_name='唱片公司')),
            ],
            options={
                'ordering': ['release', 'release_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='RecordCover',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(height_field='height', null=True, storage=portal.models.FileStorage(), upload_to=portal.models.record_cover_upload_to, verbose_name='图片', width_field='width')),
                ('width', models.PositiveIntegerField(blank=True, null=True)),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='portal.Record')),
            ],
        ),
        migrations.CreateModel(
            name='RecordImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(height_field='height', null=True, storage=portal.models.FileStorage(), upload_to=portal.models.record_images_upload_to, verbose_name='图片', width_field='width')),
                ('width', models.PositiveIntegerField(blank=True, null=True)),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.Record')),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track', models.CharField(max_length=128, verbose_name='序号')),
                ('title', models.CharField(max_length=128, verbose_name='标题')),
                ('lyricist', models.CharField(blank=True, max_length=128, null=True, verbose_name='作词')),
                ('composer', models.CharField(blank=True, max_length=128, null=True, verbose_name='作曲')),
                ('arranger', models.CharField(blank=True, max_length=128, null=True, verbose_name='编曲')),
                ('vocalist', models.CharField(blank=True, max_length=128, null=True, verbose_name='和音')),
                ('producer', models.CharField(blank=True, max_length=128, null=True, verbose_name='监制')),
                ('bandsman', models.TextField(blank=True, null=True, verbose_name='乐手')),
                ('description', models.TextField(blank=True, null=True, verbose_name='说明')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('artists', models.ManyToManyField(blank=True, to='portal.Artist', verbose_name='歌手')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.Record')),
            ],
        ),
        migrations.AlterOrderWithRespectTo(
            name='song',
            order_with_respect_to='record',
        ),
    ]
