# Generated by Django 2.0.3 on 2018-05-29 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_auto_20180516_1514'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='song',
            options={'ordering': ['track']},
        ),
        migrations.AlterOrderWithRespectTo(
            name='song',
            order_with_respect_to=None,
        ),
    ]
