# Generated by Django 2.0.6 on 2018-06-28 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_auto_20180627_0745'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='record',
            options={'ordering': ['year', 'release_order', 'title']},
        ),
        migrations.RenameField(
            model_name='record',
            old_name='release',
            new_name='year',
        ),
    ]
