# Generated by Django 5.0.7 on 2024-08-05 15:12

import django.db.models.deletion
import portal.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0006_auto_20180628_0105'),
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('comment', models.CharField(max_length=255)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'work',
            },
        ),
        migrations.CreateModel(
            name='WorkType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'work_type',
            },
        ),
        migrations.AlterField(
            model_name='artist',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='artistavatar',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='artistavatar',
            name='image',
            field=portal.models.TryExceptImageField(height_field='height', null=True, storage=portal.models.FileStorage(), upload_to=portal.models.artist_avatar_upload_to, verbose_name='图片', width_field='width'),
        ),
        migrations.AlterField(
            model_name='artistimages',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='artistimages',
            name='image',
            field=portal.models.TryExceptImageField(height_field='height', null=True, storage=portal.models.FileStorage(), upload_to=portal.models.artist_images_upload_to, verbose_name='图片', width_field='width'),
        ),
        migrations.AlterField(
            model_name='company',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='logimportartist',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='logimportrecord',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='record',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='recordcover',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='recordcover',
            name='image',
            field=portal.models.TryExceptImageField(height_field='height', null=True, storage=portal.models.FileStorage(), upload_to=portal.models.record_cover_upload_to, verbose_name='图片', width_field='width'),
        ),
        migrations.AlterField(
            model_name='recordimages',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='recordimages',
            name='image',
            field=portal.models.TryExceptImageField(height_field='height', null=True, storage=portal.models.FileStorage(), upload_to=portal.models.record_images_upload_to, verbose_name='图片', width_field='width'),
        ),
        migrations.AlterField(
            model_name='song',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='LSongWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('song', models.ForeignKey(db_column='song', on_delete=django.db.models.deletion.CASCADE, to='portal.song')),
                ('work', models.ForeignKey(db_column='work', on_delete=django.db.models.deletion.CASCADE, to='portal.work')),
            ],
            options={
                'db_table': 'l_song_work',
            },
        ),
        migrations.CreateModel(
            name='LRecordWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('record', models.ForeignKey(db_column='record', on_delete=django.db.models.deletion.CASCADE, to='portal.record')),
                ('work', models.ForeignKey(db_column='work', on_delete=django.db.models.deletion.CASCADE, to='portal.work')),
            ],
            options={
                'db_table': 'l_record_work',
            },
        ),
        migrations.AddField(
            model_name='work',
            name='type',
            field=models.ForeignKey(blank=True, db_column='type', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='portal.worktype'),
        ),
    ]
