# Generated by Django 5.0.7 on 2024-08-08 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0007_workertype_alter_artist_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recordworker',
            options={'verbose_name': '唱片参与者', 'verbose_name_plural': '唱片参与者'},
        ),
        migrations.AlterModelOptions(
            name='songworker',
            options={'verbose_name': '歌曲参与者', 'verbose_name_plural': '歌曲参与者'},
        ),
        migrations.RemoveField(
            model_name='recordworker',
            name='last_updated',
        ),
        migrations.RemoveField(
            model_name='recordworker',
            name='order',
        ),
        migrations.RemoveField(
            model_name='songworker',
            name='last_updated',
        ),
        migrations.RemoveField(
            model_name='songworker',
            name='order',
        ),
    ]
