# Generated by Django 5.1 on 2024-08-09 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0008_alter_recordworker_options_alter_songworker_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='mixer',
        ),
        migrations.RemoveField(
            model_name='record',
            name='producer',
        ),
        migrations.RemoveField(
            model_name='record',
            name='recorder',
        ),
        migrations.RemoveField(
            model_name='song',
            name='arranger',
        ),
        migrations.RemoveField(
            model_name='song',
            name='composer',
        ),
        migrations.RemoveField(
            model_name='song',
            name='lyricist',
        ),
        migrations.RemoveField(
            model_name='song',
            name='producer',
        ),
        migrations.RemoveField(
            model_name='song',
            name='vocalist',
        ),
        migrations.AlterField(
            model_name='recordworker',
            name='name',
            field=models.CharField(help_text='/分割', max_length=128, verbose_name='名称'),
        ),
        migrations.AlterField(
            model_name='songworker',
            name='name',
            field=models.CharField(help_text='/分割', max_length=128, verbose_name='名称'),
        ),
    ]
